---accounting

CREATE SCHEMA IF NOT EXISTS accounting;

--DROP TABLE accounting.accounting_expense_type;
CREATE TABLE accounting.accounting_expense_type (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
	created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_accounting_expense_type_id PRIMARY KEY (id),
	CONSTRAINT fk_accounting_expense_type_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_accounting_expense_type_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE accounting.accounting_fuel_order_type;
CREATE TABLE accounting.accounting_fuel_order_type (
    id BIGINT NOT NULL,
	serial_code VARCHAR(2) NOT NULL,
    name VARCHAR(50) NOT NULL,
 	cost_per_gallon NUMERIC(12, 2) NOT NULL,
 	created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_accounting_fuel_order_type_id PRIMARY KEY (id),
	CONSTRAINT fk_accounting_fuel_order_type_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_accounting_fuel_order_type_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE accounting.accounting_fuel_price_change_history;
CREATE TABLE accounting.accounting_fuel_price_change_history (
    id BIGINT  NOT NULL,
    accounting_fuel_order_type_id BIGINT NOT NULL,
	cost_per_gallon NUMERIC(10,2) NOT NULL,
	created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_accounting_fuel_price_change_history_id PRIMARY KEY (id),
    CONSTRAINT fk_accounting_fuel_price_change_history_fuel_order_type_id FOREIGN KEY (accounting_fuel_order_type_id) REFERENCES accounting.accounting_fuel_order_type(id),
    CONSTRAINT fk_accounting_fuel_price_change_history_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_accounting_fuel_price_change_history_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE accounting.accounting_expense;
CREATE TABLE accounting.accounting_expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    shipment_freight_id BIGINT NOT NULL,
    accounting_expense_type_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    description TEXT,
    expense_date DATE NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_accounting_expense_id PRIMARY KEY (id),
    CONSTRAINT fk_accounting_expense_shipment_freight_id FOREIGN KEY (shipment_freight_id) REFERENCES shipment.shipment_freight(id),
    CONSTRAINT fk_accounting_expense_accounting_expense_type_id FOREIGN KEY (accounting_expense_type_id) REFERENCES accounting.accounting_expense_type(id),
    CONSTRAINT fk_accounting_expense_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_accounting_expense_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE accounting.accounting_fuel_order;
CREATE TABLE accounting.accounting_fuel_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    accounting_fuel_order_type_id BIGINT NOT NULL,
    setting_currency_id BIGINT NOT NULL,
	shipment_project_contract_id BIGINT NOT NULL,
    business_partner_provider_transport_vehicle_id BIGINT NOT NULL,
    business_partner_fuel_order_issuer_id BIGINT NOT NULL,
    setting_gas_station_id BIGINT NOT NULL,
    business_partner_provider_driver_id BIGINT,
    quantity_gallon NUMERIC(12, 2) NOT NULL,
    cost_per_gallon NUMERIC(12, 2) NOT NULL,
    total_cost NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    issued_date TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_accounting_fuel_order_id PRIMARY KEY (id),
	CONSTRAINT fk_accounting_fuel_order_shipment_project_contract FOREIGN KEY (shipment_project_contract_id) REFERENCES shipment.shipment_project_contract(id),
    CONSTRAINT fk_accounting_fuel_order_accounting_fuel_order_type_id FOREIGN KEY (accounting_fuel_order_type_id) REFERENCES accounting.accounting_fuel_order_type(id),
    CONSTRAINT fk_accounting_fuel_order_setting_currency_id FOREIGN KEY (setting_currency_id) REFERENCES setting.setting_currency(id),
    CONSTRAINT fk_accounting_fuel_order_business_partner_transport_vehicle_id FOREIGN KEY (business_partner_provider_transport_vehicle_id) REFERENCES business_partner.business_partner_provider_transport_vehicle(id),
    CONSTRAINT fk_accounting_fuel_order_business_partner_fuel_order_issuer_id FOREIGN KEY (business_partner_fuel_order_issuer_id) REFERENCES business_partner.business_partner_fuel_order_issuer(id),
    CONSTRAINT fk_accounting_fuel_order_setting_gas_station_id FOREIGN KEY (setting_gas_station_id) REFERENCES setting.setting_gas_station(id),
    CONSTRAINT fk_accounting_fuel_order_business_partner_provider_driver_id FOREIGN KEY (business_partner_provider_driver_id) REFERENCES business_partner.business_partner_provider_driver(id),
    CONSTRAINT fk_accounting_fuel_order_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_accounting_fuel_order_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);