CREATE SCHEMA IF NOT EXISTS business_partner;

--DROP TABLE business_partner.business_partner_provider_profile_type;
CREATE TABLE business_partner.business_partner_provider_profile_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_profile_type_id PRIMARY KEY (id)
);

--DROP TABLE business_partner.business_partner_provider_profile_category;
CREATE TABLE business_partner.business_partner_provider_profile_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_profile_category_id PRIMARY KEY (id)
);

--DROP TABLE business_partner.business_partner_position_type;
CREATE TABLE business_partner.business_partner_position_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_position_type_id PRIMARY KEY (id)
);

--DROP TABLE business_partner.business_partner_transport_vehicle_status_type;
CREATE TABLE business_partner.business_partner_transport_vehicle_status_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_transport_vehicle_status_type_id PRIMARY KEY (id)
);

--DROP TABLE business_partner.business_partner_fuel_order_issuer;
CREATE TABLE business_partner.business_partner_fuel_order_issuer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(100) NOT NULL,
    percentage_overprice NUMERIC(5,2) NOT NULL DEFAULT 0.00,
    is_default BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_fuel_order_issuer_id PRIMARY KEY (id)
);

--DROP TABLE business_partner.business_partner_provider_profile;
CREATE TABLE business_partner.business_partner_provider_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    business_partner_provider_profile_type_id BIGINT NOT NULL,
    business_partner_provider_profile_category_id BIGINT NOT NULL,
	general_city_id BIGINT NOT NULL,
    legal_id VARCHAR(20) NOT NULL,
    business_name VARCHAR(100) NOT NULL,
    legal_name VARCHAR(100), -- opcional
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    address TEXT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_profile_id PRIMARY KEY (id),
    CONSTRAINT fk_business_partner_provider_profile_general_city_id FOREIGN KEY (general_city_id) REFERENCES general.general_city(id),
    CONSTRAINT fk_business_partner_provider_profile_type FOREIGN KEY (business_partner_provider_profile_type_id) REFERENCES business_partner.business_partner_provider_profile_type(id),
    CONSTRAINT fk_business_partner_provider_profile_category FOREIGN KEY (business_partner_provider_profile_category_id) REFERENCES business_partner.business_partner_provider_profile_category(id),
    CONSTRAINT fk_business_partner_provider_profile_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_business_partner_provider_profile_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE business_partner.business_partner_provider_profile_contact_person;
CREATE TABLE business_partner.business_partner_provider_profile_contact_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    business_partner_provider_profile_id BIGINT NOT NULL,
    business_partner_position_type_id BIGINT NOT NULL,
    national_id VARCHAR(20),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_profile_contact_person_id PRIMARY KEY (id),
    CONSTRAINT fk_business_partner_provider_profile_contact_person FOREIGN KEY (business_partner_provider_profile_id) REFERENCES business_partner.business_partner_provider_profile(id),
    CONSTRAINT fk_business_partner_profile_contact_person_position_type_id FOREIGN KEY (business_partner_position_type_id) REFERENCES business_partner.business_partner_position_type(id),
    CONSTRAINT fk_business_partner_provider_profile_contact_person_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_business_partner_provider_profile_contact_person_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);


--DROP TABLE business_partner.business_partner_provider_driver;
CREATE TABLE business_partner.business_partner_provider_driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    business_partner_provider_profile_id BIGINT,
    national_id VARCHAR(20),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    date_of_birth DATE,
    nationality VARCHAR(50) NOT NULL,
    hire_date DATE,
    end_date DATE,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_driver_id PRIMARY KEY (id),
    CONSTRAINT fk_business_partner_provider_driver_profile_provider_profile FOREIGN KEY (business_partner_provider_profile_id) REFERENCES business_partner.business_partner_provider_profile(id),
    CONSTRAINT fk_bbusiness_partner_provider_driver_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_business_partner_provider_driver_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE business_partner.business_partner_provider_transport_vehicle;
CREATE TABLE business_partner.business_partner_provider_transport_vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    business_partner_provider_profile_id BIGINT NOT NULL,
    business_partner_provider_driver_id BIGINT,
    plate_number VARCHAR(20) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INTEGER NOT NULL,
    color VARCHAR(30) NOT NULL,
    vin VARCHAR(50) NOT NULL,
    axles INTEGER NOT NULL,
    description TEXT,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_business_partner_provider_transport_vehicle_id PRIMARY KEY (id),
    CONSTRAINT fk_business_partner_provider_transport_vehicle_provider_profile FOREIGN KEY (business_partner_provider_profile_id) REFERENCES business_partner.business_partner_provider_profile(id),
    CONSTRAINT fk_business_partner_provider_transport_vehicle_provider_driver FOREIGN KEY (business_partner_provider_driver_id) REFERENCES business_partner.business_partner_provider_driver(id),
    CONSTRAINT fk_business_partner_provider_transport_vehicle_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_business_partner_provider_transport_vehicle_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);


-------------------------------------------
---INSERT IN TO TABLES
-------------------------------------------

-- INSERT business_partner_provider_profile_type
INSERT INTO business_partner.business_partner_provider_profile_type (name, is_active) VALUES
('Transporte Nacional', true),
('Transporte Internacional', true),
('Proveedores de Combustible', true),
('Mecánica y Taller', true),
('Logística y Almacenaje', false);

-- INSERT business_partner_provider_profile_category
INSERT INTO business_partner.business_partner_provider_profile_category (name, is_active) VALUES
('Persona Natural', true),
('Persona Jurídica', true),
('Cooperativa', true),
('Asociación de Transporte', false);

-- INSERT business_partner_position_type
INSERT INTO business_partner.business_partner_position_type (name, is_active) VALUES
('Conductor', true),
('Ayudante', true),
('Supervisor de Ruta', true),
('Mecánico', true),
('Administrador', false);

-- INSERT business_partner_transport_vehicle_status_type
INSERT INTO business_partner.business_partner_transport_vehicle_status_type (name, is_active) VALUES
('Disponible', true),
('En Ruta', true),
('En Mantenimiento', true),
('Baja Temporal', false),
('Fuera de Servicio', false);

-- INSERT business_partner_fuel_order_issuer
INSERT INTO business_partner.business_partner_fuel_order_issuer (name, percentage_overprice, is_default) VALUES
('Transportes Honduras S.A.', 0.00, true),
('Transporte Osorio', 2.50, false);

