CREATE SCHEMA IF NOT EXISTS customer;

--DROP TABLE customer.customer_profile;
CREATE TABLE customer.customer_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	general_city_id BIGINT NOT NULL,
    legal_id VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    legal_name VARCHAR(100),
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    address TEXT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_customer_profile_id PRIMARY KEY (id),
	CONSTRAINT fk_customer_profile_general_city_id FOREIGN KEY (general_city_id) REFERENCES general.general_city(id),
    CONSTRAINT fk_customer_profile_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_customer_profile_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE customer.customer_contact_person;
CREATE TABLE customer.customer_contact_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_profile_id BIGINT NOT NULL,
    national_id VARCHAR(20),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_customer_contact_person_id PRIMARY KEY (id),
    CONSTRAINT fk_customer_contact_person_profile_customer_profile FOREIGN KEY (customer_profile_id) REFERENCES customer.customer_profile(id),
    CONSTRAINT fk_customer_contact_person_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_customer_contact_person_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE customer.customer_warehouse;
CREATE TABLE customer.customer_warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_profile_id BIGINT NOT NULL,
	general_city_id BIGINT NOT NULL,
    code INT NOT NULL,
    name VARCHAR(100) NOT NULL,
	address TEXT NOT NULL,
    longitud DECIMAL(11, 8) NOT NULL,
    latitud DECIMAL(11, 8) NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_customer_warehouse_id PRIMARY KEY (id),
    CONSTRAINT fk_customer_warehouse_profile_customer_profile_id FOREIGN KEY (customer_profile_id) REFERENCES customer.customer_profile(id),
	CONSTRAINT fk_customer_warehouse_general_city_id FOREIGN KEY (general_city_id) REFERENCES general.general_city(id),
    CONSTRAINT fk_customer_warehouse_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_customer_warehouse_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);
