---GENERAL

CREATE SCHEMA IF NOT EXISTS general;


-- DROP TABLE general.general_country
CREATE TABLE general.general_country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(150) NOT NULL,
    code VARCHAR(10),
    iso_code VARCHAR(10),
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_general_country_id PRIMARY KEY (id),
    CONSTRAINT fk_general_country_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_general_country_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE general.general_region
CREATE TABLE general.general_region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(150) NOT NULL,
    country_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_general_region_id PRIMARY KEY (id),
    CONSTRAINT fk_general_region_country_id FOREIGN KEY (country_id) REFERENCES general.general_country(id),
    CONSTRAINT fk_general_region_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_general_region_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE general.general_city
CREATE TABLE general.general_city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name VARCHAR(150) NOT NULL,
    region_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_general_city_id PRIMARY KEY (id),
    CONSTRAINT fk_general_city_region_id FOREIGN KEY (region_id) REFERENCES general.general_region(id),
    CONSTRAINT fk_general_city_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_general_city_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE general.general_error_log
CREATE TABLE general.general_error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    project VARCHAR(255),
    class VARCHAR(255),
    method VARCHAR(255),
    line_number INT,
    error_description TEXT,
    created_date TIMESTAMP,
    CONSTRAINT pk_general_error_log_id PRIMARY KEY (id)
);

--INSERT general.general_country
INSERT INTO general.general_country (name, code, iso_code, created_by, created_date, is_active)
VALUES 
('Honduras', 'HN', 'HND', 1, CURRENT_TIMESTAMP, true),
('Guatemala', 'GT', 'GTM', 1, CURRENT_TIMESTAMP, true),
('El Salvador', 'SV', 'SLV', 1, CURRENT_TIMESTAMP, true),
('Nicaragua', 'NI', 'NIC', 1, CURRENT_TIMESTAMP, true),
('Panamá', 'PA', 'PAN', 1, CURRENT_TIMESTAMP, false);

--INSERT general.general_region
INSERT INTO general.general_region (name, country_id, created_by, created_date, is_active)
VALUES 
('Francisco Morazán', 1, 1, CURRENT_TIMESTAMP, true),
('Cortés', 1, 1, CURRENT_TIMESTAMP, true),
('Ciudad de Guatemala', 2, 1, CURRENT_TIMESTAMP, true),
('San Salvador', 3, 1, CURRENT_TIMESTAMP, true),
('Managua', 4, 1, CURRENT_TIMESTAMP, true);

--INSERT general.general_city
INSERT INTO general.general_city (name, region_id, created_by, created_date, is_active)
VALUES 
('Tegucigalpa', 1, 1, CURRENT_TIMESTAMP, true),
('San Pedro Sula', 2, 1, CURRENT_TIMESTAMP, true),
('Guatemala City', 3, 1, CURRENT_TIMESTAMP, true),
('San Salvador', 4, 1, CURRENT_TIMESTAMP, true),
('Managua', 5, 1, CURRENT_TIMESTAMP, true);


