CREATE SCHEMA IF NOT EXISTS setting;

--DROP TABLE setting.setting_currency;
CREATE TABLE setting.setting_currency (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_ssetting_currency_id PRIMARY KEY (id)
);

--DROP TABLE setting.setting_gas_station;
CREATE TABLE setting.setting_gas_station (
    id BIGINT NOT NULL,
	general_city_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
	address TEXT NOT NULL,
	created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_setting_gas_station_id PRIMARY KEY (id),
	CONSTRAINT fk_setting_gas_station_general_city_id FOREIGN KEY (general_city_id) REFERENCES general.general_city(id)
);

-- DROP TABLE setting.setting_dispatch_branch;
CREATE TABLE setting.setting_dispatch_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	general_city_id BIGINT NOT NULL,
    code INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
	address TEXT NOT NULL,
    longitud DECIMAL(11, 8) NOT NULL,
    latitud DECIMAL(11, 8) NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_setting_dispatch_branch_id PRIMARY KEY (id),
    CONSTRAINT fk_setting_dispatch_branch_general_city_id FOREIGN KEY (general_city_id) REFERENCES general.general_city(id),
    CONSTRAINT fk_setting_dispatch_branch_created_by_user FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_setting_dispatch_branch_modified_by_user FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE setting.setting_freight_pricing_per_customer;
CREATE TABLE setting.setting_freight_pricing_per_customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    setting_dispatch_branch_id BIGINT NOT NULL,
    customer_warehouse_id BIGINT NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    cost NUMERIC(12, 2) NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_setting_freight_pricing_per_customer_id PRIMARY KEY (id),
    CONSTRAINT fk_setting_freight_dispatch_branch FOREIGN KEY (setting_dispatch_branch_id) REFERENCES setting.setting_dispatch_branch(id),
    CONSTRAINT fk_setting_freight_customer_warehouse FOREIGN KEY (customer_warehouse_id) REFERENCES customer.customer_warehouse(id),
    CONSTRAINT fk_setting_freight_created_by_user FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_setting_freight_modified_by_user FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-------------------------------------------
---INSERT IN TO TABLES
-------------------------------------------

INSERT INTO setting.setting_currency (id, name, is_active) VALUES
(1, 'Lempira (HNL)', true),
(2, 'Dólar Estadounidense (USD)', true),
(3, 'Euro (EUR)', true),
(4, 'Peso Mexicano (MXN)', false),
(5, 'Colón Costarricense (CRC)', false);


INSERT INTO setting.setting_gas_station (id, general_city_id, name, address, created_by, created_date, modified_by, modified_date, is_active
) VALUES
(1, 1, 'Puma Tegucigalpa Centro', 'Colonia Centro, Calle Principal, Tegucigalpa', 100, NOW(), NULL, NULL, true),
(2, 2, 'Uno San Pedro Norte', 'Barrio El Benque, San Pedro Sula', 100, NOW(), NULL, NULL, true),
(3, 1, 'Texaco El Hatillo', 'Carretera hacia El Hatillo, Tegucigalpa', 100, NOW(), NULL, NULL, true),
(4, 3, 'Gasolinera Shell La Ceiba', 'Bulevar 15 de Septiembre, La Ceiba', 100, NOW(), NULL, NULL, false);

