CREATE SCHEMA IF NOT EXISTS shipment;

--DROP TABLE shipment.shipment_freight_status;
CREATE TABLE shipment.shipment_freight_status (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_freight_status_id PRIMARY KEY (id)
);

--DROP TABLE shipment.shipment_freight_type;
CREATE TABLE shipment.shipment_freight_type (
    id BIGINT  NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_freight_type_id PRIMARY KEY (id)
);


--DROP TABLE shipment.freight_product_type;
CREATE TABLE shipment.freight_product_type (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_freight_product_type_id PRIMARY KEY (id)
);

--DROP TABLE shipment.shipment_rotulation_type;
CREATE TABLE shipment.shipment_rotulation_type (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_rotulation_type_id PRIMARY KEY (id)
);

--DROP TABLE shipment.shipment_gps_device;
CREATE TABLE shipment.shipment_gps_device (
    id BIGINT NOT NULL,
    customer_profile_id BIGINT,
    serial_number VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
	registration_date TIMESTAMP NOT NULL,
	created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_gps_device_id PRIMARY KEY (id),
	CONSTRAINT fk_shipment_gps_device_customer_profile FOREIGN KEY (customer_profile_id) REFERENCES customer.customer_profile(id),
	CONSTRAINT fk_shipment_gps_device_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_shipment_gps_device_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

-- DROP TABLE shipment.shipment_project_contract_transport_vehicle;
CREATE TABLE shipment.shipment_project_contract_transport_vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    shipment_project_contract_id BIGINT NOT NULL,
    business_partner_transport_vehicle_id BIGINT NOT NULL,
    shipment_rotulation_type_id BIGINT NOT NULL,
    shipment_gps_device_id BIGINT,
    rotulation_number INT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_project_contract_transport_vehicle_id PRIMARY KEY (id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_project_contract FOREIGN KEY (shipment_project_contract_id) REFERENCES shipment.shipment_project_contract(id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_vehicle FOREIGN KEY (business_partner_transport_vehicle_id) REFERENCES business_partner.business_partner_provider_transport_vehicle(id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_rotulation_type FOREIGN KEY (shipment_rotulation_type_id) REFERENCES shipment.shipment_rotulation_type(id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_gps_device FOREIGN KEY (shipment_gps_device_id) REFERENCES shipment.shipment_gps_device(id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_shipment_project_contract_transport_vehicle_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);


--DROP TABLE shipment.shipment_project_contract;
CREATE TABLE shipment.shipment_project_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_profile_id BIGINT NOT NULL,
    business_partner_fuel_order_issuer_id BIGINT NOT NULL,
    setting_dispatch_branch_id BIGINT NOT NULL,
    contract_number BIGINT NOT NULL,
	contract_description VARCHAR(500) NOT NULL,
	comment VARCHAR(500),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    expected_freight_quantity INT NOT NULL,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_project_contract_id PRIMARY KEY (id),
    CONSTRAINT fk_shipment_project_contract_customer_profile FOREIGN KEY (customer_profile_id) REFERENCES customer.customer_profile(id),
    CONSTRAINT fk_shipment_project_contract_business_partner_fuel_order_issuer FOREIGN KEY (business_partner_fuel_order_issuer_id) REFERENCES business_partner.business_partner_fuel_order_issuer(id),
    CONSTRAINT fk_shipment_project_contract_setting_dispatch_branch FOREIGN KEY (setting_dispatch_branch_id) REFERENCES setting.setting_dispatch_branch(id),
    CONSTRAINT fk_shipment_project_contract_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_shipment_project_contract_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE shipment.shipment_freight;
CREATE TABLE shipment.shipment_freight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    shipment_project_contract_id BIGINT NOT NULL,
    business_partner_provider_transport_vehicle_id BIGINT NOT NULL,
    customer_warehouse_id BIGINT NOT NULL,
    business_partner_provider_driver_id BIGINT NOT NULL,
    shipment_freight_status_id BIGINT NOT NULL,
    shipment_freight_type_id BIGINT NOT NULL,
    freight_product_type_id BIGINT NULL,
	freight_product_quantity BIGINT NULL,
    price NUMERIC(12, 2) NOT NULL,
    cost NUMERIC(12, 2) NOT NULL,
    observations TEXT,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_freight_id PRIMARY KEY (id),
    CONSTRAINT fk_shipment_freight_project_contract FOREIGN KEY (shipment_project_contract_id) REFERENCES shipment.shipment_project_contract(id),
    CONSTRAINT fk_shipment_freight_business_partner_provider_transport_vehicle FOREIGN KEY (business_partner_provider_transport_vehicle_id) REFERENCES business_partner.business_partner_provider_transport_vehicle(id),
    CONSTRAINT fk_shipment_freight_customer_warehouse FOREIGN KEY (customer_warehouse_id) REFERENCES customer.customer_warehouse(id),
    CONSTRAINT fk_shipment_freight_business_partner_provider_driver FOREIGN KEY (business_partner_provider_driver_id) REFERENCES business_partner.business_partner_provider_driver(id),
    CONSTRAINT fk_shipment_freight_status FOREIGN KEY (shipment_freight_status_id) REFERENCES shipment.shipment_freight_status(id),
    CONSTRAINT fk_shipment_freight_type FOREIGN KEY (shipment_freight_type_id) REFERENCES shipment.shipment_freight_type(id),
    CONSTRAINT fk_shipment_freight_product_type FOREIGN KEY (freight_product_type_id) REFERENCES shipment.freight_product_type(id),
    CONSTRAINT fk_shipment_freight_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_shipment_freight_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);

--DROP TABLE shipment.shipment_freight_status_log;
CREATE TABLE shipment.shipment_freight_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    shipment_freight_id BIGINT NOT NULL,
    shipment_freight_status_id BIGINT NOT NULL,
    comments TEXT,
    created_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_by BIGINT,
    modified_date TIMESTAMP,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_shipment_freight_status_log_id PRIMARY KEY (id),
    CONSTRAINT fk_shipment_freight_status_log_freight FOREIGN KEY (shipment_freight_id) REFERENCES shipment.shipment_freight(id),
    CONSTRAINT fk_shipment_freight_status_log_status FOREIGN KEY (shipment_freight_status_id) REFERENCES shipment.shipment_freight_status(id),
    CONSTRAINT fk_shipment_freight_status_log_created_by FOREIGN KEY (created_by) REFERENCES auth.auth_user(id),
    CONSTRAINT fk_shipment_freight_status_log_modified_by FOREIGN KEY (modified_by) REFERENCES auth.auth_user(id)
);










