services:
  fleetmanager.service.admin:
    image: malcommedina/fleetmanager-service-admin:latest
    restart: always
    build:
      context: .
      dockerfile: src/api/Service.Admin/Dockerfile

  fleetmanager.service.cdn:
    image: nginx:latest
    restart: always