services:
  fleetmanager.service.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=${PROJECT_ASPNETCORE_ENVIRONMENT}
      - TZ=${PROJECT_TIMEZONE}
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_DOMAIN=${PROJECT_DOMAIN}
      - PROJECT_DB_CONNECTION_STRING=${PROJECT_DB_CONNECTION_STRING}
      - PROJECT_SENTRY_KEY=${PROJECT_SENTRY_KEY}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SSL=${SMTP_SSL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT}
    volumes:
      - ./media:/app/media
    ports:
       - "6070:8080"

  fleetmanager.service.cdn:
    image: nginx:latest
    ports:
      - "6071:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/usr/share/nginx/html/media